### ISSUE TITLE
How to extract Features?

### ISSUE THREAD

**Issue by SecretActionDev** [gessi-chatbots/t-frex#1]
Hello there, 

I'm a little bit confused on how can I use TFREX to extract features. I using the model in this link: https://huggingface.co/quim-motger/t-frex-bert-large-uncased to extract features from a description based on the example provided however it only outputs token classification and no feature. how would we use the your model to extract features similar to the ones in your paper?

Cheers,

**Comment by quim-motger** [comment]
Dear colleague,

First of all, thank you very much for your interest in T-FREX.

The README file includes instructions on how to use T-FREX models available on HuggingFace for model inference. You can check these instructions in the Section [Model inference](https://github.com/gessi-chatbots/t-frex?tab=readme-ov-file#model-inference).

As you mention, the feature extraction task in the context of T-FREX is defined as a token classification task, where each token is classified with one of the following tags:

- _B-feature_: the token pertains to the beginning of a feature expression
- _I-feature_: the token pertains to any part (except the first token) of a feature expression
- _O_: the token does not pertain to any part of a feature

This formulation is better explained in our publications:

- Q. Motger, A. Miaschi, F. Dell'Orletta, X. Franch and J. Marco, "T-FREX: A Transformer-based Feature Extraction Method from Mobile App Reviews," 2024 IEEE International Conference on Software Analysis, Evolution and Reengineering (SANER), Rovaniemi, Finland, 2024, pp. 227-238, doi: [10.1109/SANER60148.2024.00030](https://doi.org/10.1109/SANER60148.2024.00030).

- Q. Motger, A. Miaschi, F. Dell'Orletta, X. Franch and J. Marco, "Leveraging Large Language Models for Mobile App Review Feature Extraction". arXiv [Cs.CL]. Retrieved from http://arxiv.org/abs/2408.01063 (Pre-print)

Please do not hesitate to ask again if you have further questions.

Best regards,

Quim

**Comment by SecretActionDev** [comment]
Thank you very much!

I was just re-reading the paper and your manuscript titled "Leveraging Large Language Models for Mobile App
Review Feature Extraction" (Great job btw :D) and it all makes sense now. 

Regards, 

E.
